### PR TITLE
Update freetype and harfbuzz

### PR DESCRIPTION
**Pull request by hjanetzek**

### CODE REVIEW

**Comment by karimnaaji** [comment]
Can we update the freetype folder with the appropriate version?

**Comment by matteblair** [comment]
Hooooly cow! How is there so much deleted from freetype and harfbuzz?

**Comment by tallytalwar** [comment]
Sometimes we get lucky!! I see a lot of bookkeeping which got deleted. Not much big code changes.

My first reaction was yay build times!! but....

**Comment by karimnaaji** [comment]
No there's not that much being deleted, I suspect github to be failing giving appropriate diff numbers because the folder has been renamed from `freetype2.6` to `freetype`.

**Comment by karimnaaji** [comment]
And some other `.html` files are not part of it anymore

**Pull request merged**
